// types for houses
export const FETCHING_HOUSES = "FETCHING_HOUSES";
export const FETCHING_HOUSES_SUCCESS = "FETCHING_PROFILES_SUCCESS";
export const FETCHING_HOUSES_ERROR = "FETCHING_PROFILES_ERROR";
export const FETCHING_HOUSE = "FETCHING_PROFILE";
export const FETCHING_HOUSE_SUCCESS = "FETCHING_PROFILE_SUCCESS";
export const FETCHING_HOUSE_ERROR = "FETCHING_PROFILE_ERROR";
// types for characters
export const FETCHING_CHARACTER = "FETCHING_CHARACTER";
export const FETCHING_CHARACTER_SUCCESS = "FETCHING_CHARACTER_SUCCESS";
export const FETCHING_CHARACTER_ERROR = "FETCHING_CHARACTER_ERROR";
export const FETCHING_CHARACTERS = "FETCHING_CHARACTERS";
export const FETCHING_CHARACTERS_SUCCESS = "FETCHING_CHARACTERS_SUCCESS";
export const FETCHING_CHARACTERS_ERROR = "FETCHING_CHARACTERS_ERROR";
export const SET_PAGINATION = "SET_PAGINATION";
export const SET_HOUSE = "SET_HOUSE";
