// types for houses
export const FETCHING_HOUSES = "FETCHING_HOUSES";
export const FETCHING_HOUSES_SUCCESS = "FETCHING_PROFILES_SUCCESS";
export const FETCHING_HOUSES_ERROR = "FETCHING_PROFILES_ERROR";
export const FETCHING_HOUSE = "FETCHING_PROFILE";
export const FETCHING_HOUSE_SUCCESS = "FETCHING_PROFILE_SUCCESS";
export const FETCHING_HOUSE_ERROR = "FETCHING_PROFILE_ERROR";
// types for characters
export const FETCHING_CHARACTER = "FETCHING_ACTIVITIES";
export const FETCHING_CHARACTER_SUCCESS = "FETCHING_ACTIVITIES_SUCCESS";
export const FETCHING_CHARACTER_ERROR = "FETCHING_ACTIVITIES_ERROR";
